### ISSUE TITLE
Colab - Runtime disconnected

### ISSUE THREAD

**Issue by ronaldyoav** [facefusion/facefusion-colab#13]
"How do I fix it? I've tried changing the custom TinyURL repeatedly, but the Colab still can't run longer?"

------------------------------------------------------------

Runtime disconnected

Your runtime has been disconnected due to executing code that is disallowed in our free of charge tier. Colab subsidizes millions of users and prioritizes interactive programming sessions while disallowing some types of usage as outlined in the [FAQ](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions). If you believe this message is in error, [file an appeal](https://colab.research.google.com/github/facefusion/facefusion-colab/blob/master/facefusion.ipynb#). Please include any relevant context about your usage.

------------------------------------------------------------

Your compute unit balance is 0. [Purchase more](https://colab.research.google.com/signup?utm_source=dialog&utm_medium=link&utm_campaign=disallowed_warning)

To connect to a new runtime, click the connect button below.

**Comment by henryruhs** [comment]
Kill your runtime and create from the latest file.
