### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by ziggyputtar** [facefusion/facefusion-colab#5]
ir syas 

Running on local URL:  http://127.0.0.1:7860/

To create a public link, set `share=True` in `launch()`.

**Comment by henryruhs** [comment]
that is an error?

**Comment by ziggyputtar** [comment]
> that is an error?

idk i am not an expert in coding and all, can you help me with this please ?

**Comment by henryruhs** [comment]
nope, it is not... join our [Discord](https://join.facefusion.io) for help and question like that.
