### ISSUE TITLE
GPU not working

### ISSUE THREAD

**Issue by rickychaka** [facefusion/facefusion-colab#7]
Need help, GPU on Google Colab not working... 

![Screenshot 2023-12-18 171742](https://github.com/facefusion/facefusion-colab/assets/125632086/97a4065e-2b18-4e39-9c3c-4c6647591f0c)

**Comment by rickychaka** [comment]
Yes, its same...


[ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error:

**Comment by azoksky** [comment]
Okay. Gotcha.. I installed 11.8 cuda toolkit on colab and it works fine now. But the sheer amount of time to set it up  is awful. Till we get onnxruntime supporting 12.2 cuda, this would be the way to go I suppose. I guess nothing beyond 11.8 supports onnxruntime. My 8gb local system runs well though. I will continue to run it locally. Thank u for the support.

**Comment by azoksky** [comment]
> I tried to solve it with nightly pytorch and nightly onnxruntime but without luck.

Okay. Gotcha.. I installed 11.8 cuda toolkit on colab and it works fine now. But the sheer amount of time to set it up  is awful. Till we get onnxruntime supporting 12.2 cuda, this would be the way to go I suppose. I guess nothing beyond 11.8 supports onnxruntime. My 8gb local system runs well though. I will continue to run it locally. Thank u for the support.

**Comment by henryruhs** [comment]
Pytorch actual supports CUDA 12 now... let's upvote the related onnxruntime issue

https://github.com/microsoft/onnxruntime/issues/18850

**Comment by azoksky** [comment]
Sure..thank u

**Comment by henryruhs** [comment]
It works again...
