### ISSUE TITLE
Google Cloud has begun to fail

### ISSUE THREAD

**Issue by aiise117** [facefusion/facefusion-colab#8]
Google Cloud has started to crack down on the operation of such code, and free users can no longer run it perfectly. May I ask if you can run it on the Kaggle platform

**Comment by rickychaka** [comment]
yes, request facefusion on kaggle. Thanks

**Comment by henryruhs** [comment]
Nope

**Comment by aiise117** [comment]
After making changes, it will still be run by Google terminal code, indicating that this is not a code allowed to be executed at the free level!

**Comment by henryruhs** [comment]
It seems they found another approach to ban it.

**Comment by aiise117** [comment]
> 看来他们找到了另一种方法来禁止它。

I thought this was a code layer issue, there should be a way to avoid code statements that are prohibited by the platform

**Comment by aiise117** [comment]
![IMG_0682](https://github.com/facefusion/facefusion-colab/assets/114309081/0321fee9-4e3b-4065-837a-ddfb40948c1e)

**Comment by aiise117** [comment]
This can run smoothly and continuously. Just some unexpected small errors causing slow web response
